version: "3.4"

services:
  teste:
    image: juliomain/testeEnv:${TAG:-latest}
    env_file: ".env"
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:80
    environment:
      - TZ=America/Sao_Paulo